name: my-kvm CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update && sudo apt install capstone
    - name: make
      run: make
